version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  s3_service:
    build:
      context: s3_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  open_api:
    build:
      context: open_api
      dockerfile: Dockerfile

    depends_on:
      postgres:
        condition: service_healthy
      s3_service:
        condition: service_started

    ports:
      - '8080:8080'

volumes:
  postgres_data:
