version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3_service:
    build:
      context: s3_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  open_api:
    build:
      context: open_api
      dockerfile: Dockerfile

    depends_on:
      - postgres
      - s3_service
    ports:
      - '8080:8080'

volumes:
  postgres_data:
